### ISSUE TITLE
@JsonIgnore annotation not working

### ISSUE THREAD

**Issue by allnash** [payintech/play-ebean#5]
I am using the following configuration in build.sbt
- libraryDependencies += "com.github.0xbaadf00d" % "ebean-encryption" % "release~17.01"
- libraryDependencies += "io.ebean" % "ebean" % "11.14.1"
and the following in plugins.sbt
- addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.6.12")
- addSbtPlugin("com.payintech" % "sbt-play-ebean" % "18.03")

The @JsonIgnore functionality seems to be broken. :(

the method                 
     ```Json.toJson(object); ```
returns them all.

A bug?

**Comment by thibaultmeyer** [comment]
Hello @allnash 

Your issue is not related to play-ebean, neither ebean itself. But yes, it could be confusing to have a `JsonIgnore` annotation on the ebean package too.

Internally, Play Framework use the library Jackson, you have to use the annotation provided by Jackson : `com.fasterxml.jackson.annotation.JsonIgnore`.

Sincerely.

**Comment by allnash** [comment]
I will give it a try. Although I am pretty sure I did try and it failed.
